### ISSUE TITLE
API Header annotation/query error

### ISSUE THREAD

**Issue by Glfrey** [ratschlab/metagraph#421] opened 2022-08-05 17:37 UTC
Hello again,

I've constructed a graph and annotated it using the headers. However, when I query the graph back with the sequences used to construct the graph and then annotate it, I get the incorrect header returned. For example:

If my sequence is:
`var_in.1
TTCCGATCTAGACATAACATACCAGTAATCTCTAGATG`

I query it against the graph and it should return that exact header. However I get a completely different header:

```
graph_client.search("TTCCGATCTAGACATAACATACCAGTAATCTCTAGATG", discovery_threshold=1.0, query_coords=True) 
  kmer_coords  kmer_count          sample seq_description
0     [0-0-7]           8  var_in.3040331               0
````

The numbers of coordinates and counts are correct, but the header is wrong. The sequence the header refers to appears to have no k-mers in common with the queried sequence.

`>var_in.3040331
TCATTTCGTTCAGTAGCACCTGATTCCCACGATTAATGAGTAGCAAGCGAGAAACAGAGTGCTAGGAAATCCTTATCGTTGTTTGGTAAAGCACACATGCACTAGTGTCTTGAGCCATAGCGACCAAGCAGCATTCAACGCATAGCAAAACAAAAGAAATGGACAAAAGAACCAATAGAGTGGAGGATTGATAGAGAGTGGGAACTAAAATGTCAGGGGTAAGAGAACGACCTGAAAGGACGGCAACTGGTAAATATGTTATGCGAGAAATAGGTGTTGTGGGTTACATGTGTGTAACCTTGGGTTAGTCAG `

The command used to annotate was:

`metagraph annotate -p 64 -i var_DA.dbg -o Var_DA --anno-header --coordinates -v  var_DA.fasta.gz
`

I've doubled checked I'm using the same file to construct, annotate and query.

**Comment by Glfrey** [comment] 2022-08-05 18:24
Just a quick update,  this doesn't appear to be limited to the API. A regular query yields the incorrect label too:

`0	var_in.1	<var_in.3040331>:0-0-7`

**Comment by karasikov** [comment] 2022-08-05 21:50
Hi Gil! I double-checked the code but didn't find any bugs so far. The only thing I realized is that it's not going to work if the annotation labels are not distinct. Can it happen that multiple sequences have the same header in your files?

**Comment by Glfrey** [comment] 2022-08-06 09:26
Hi Mikhail, thanks for checking this out. The headers are those given from the differential assembly process where I added in “var_in” prefix in the json file. I don’t think the assembly process duplicates headers and a quick check shows me they seem to be unique. I’d be happy to share my files with you to duplicate the problem if that’d help?

**Comment by karasikov** [comment] 2022-08-06 12:17
That would be awesome! If I can repeat the process, I'll find the problem much faster. Could you share the files via google drive, for instance?

**Comment by Glfrey** [comment] 2022-08-06 14:24
Sure thing, I’ll set that up. Shall I send permissions to access to the email I have for you already?


On 6 Aug 2022, at 13:17, Mikhail Karasikov ***@***.***> wrote:

﻿

That would be awesome! If I can repeat the process, I'll find the problem much faster. Could you share the files via google drive, for instance?

**Comment by karasikov** [comment] 2022-08-06 14:25
Yeah, perfect. Thanks a lot!

**Comment by Glfrey** [comment] 2022-08-06 17:17
I uploaded the sequences and sent you and invite, let me know if there’s any issues accessing the data.

On 6 Aug 2022, at 15:25, Mikhail Karasikov ***@***.***> wrote:

﻿

Yeah, perfect. Thanks a lot!

**Comment by karasikov** [comment] 2022-08-06 20:07
I got it, thanks. I've just tested with `brwt_coord`. It seems to be working fine and returns proper labels/headers.

I'm testing now `row_diff_brwt_coord`.

Which annotation format are you working with?

PS. I've just found that it annotates headers (in fact, anything if you have many-many labels) way faster if you reduce the buffer size. Simply pass `--mem-cap-gb 1e-4` when you run `metagraph annotate` (unless you're annotating with disk-swap, then a larger buffer is needed). This will speed up that command a lot.
There is a more universal fix for this (namely, to reuse large buffers instead of doing lots of reallocations), which I'll implement a bit later, so you won't need to manually reduce the buffer size. But you can use that trick for now...

**Comment by Glfrey** [comment] 2022-08-06 20:16
Brilliant that's good news and thank you sharing the speed up trick, that's very helpful. 

I transform the coordinates using the column coordinatess:
`metagraph transform_anno -o Var_DA_transformed --anno-type column_coord Var_DA.column.annodbg -v
`

I'll go ahead and change to `brwt-cord` and test it out.

**Comment by karasikov** [comment] 2022-08-06 20:32
Hm... Actually, I did test with `column_coord` too and got the correct result.

Could you please share the full command for generating the final index, just to make sure I'm not missing something?

Thanks!

**Comment by Glfrey** [comment] 2022-08-06 20:38
Huh that's strange. 

The construction command I used was:
`metagraph annotate -p 64 -i var_DA.dbg -o Var_DA --anno-header --coordinates -v  var_DA.fasta.gz
`

**Comment by karasikov** [comment] 2022-08-06 20:40
And then ... `transform_anno`?

**Comment by Glfrey** [comment] 2022-08-06 20:42
`metagraph transform_anno -o Var_DA_transformed --anno-type column_coord Var_DA.column.annodbg -v
`

**Comment by karasikov** [comment] 2022-08-06 20:42
Also, which version of metagraph are you using?
What does `metagraph --version` say?

**Comment by karasikov** [comment] 2022-08-06 20:43
> `metagraph transform_anno -o Var_DA_transformed --anno-type column_coord Var_DA.column.annodbg -v `

Ok, all looks good to me. I did the same thing. I'll try again...

**Comment by Glfrey** [comment] 2022-08-06 20:43
`Version: 0.3.4`

**Comment by karasikov** [comment] 2022-08-06 20:44
Ok, thanks! I'll try again tomorrow and let you know.

**Comment by Glfrey** [comment] 2022-08-06 20:45
Thank you so much! I'll try different transformations and see what happens too.

**Comment by karasikov** [comment] 2022-08-07 16:06
Hi Gil, I tried again everything from scratch with the following commands and got the correct results.

```
metagraph build -p 64 -k 31 -o var ~/var_DA.fasta.gz -v
metagraph annotate -p 64 -i var.dbg -o var --anno-header --coordinates ~/var_DA.fasta.gz --mem-cap-gb 1e-5 -v
metagraph transform_anno -p 64 --anno-type column_coord -o var var.column.annodbg -v
metagraph query -i var.dbg ~/var_DA.fasta.gz -a var.column_coord.annodbg --count-labels --query-coords > results
```
```
0       var_in.1        <var_in.1>:0-0-7
...
```

I also tried that on version 0.3.4 from bioconda and it worked too. So it looks like I can't reproduce the bug on my system :(

Do these commands look equivalent to those you're running or I missed something?

PS. I've also started a PR (#423) with some other minor fixes and improvements that I figured out while testing this. These will be implemented in the next metagraph version -- 0.3.6.

**Comment by Glfrey** [comment] 2022-08-08 12:37
Hi Mikhail, thank you!  It looks to me like you're doing everything I did, which means there's probably an error on my end somewhere. I did try and rerun the process yesterday on my end but the server I'm using was very busy so I'll try again today and I'll let you know what happens. Thank you for all of your help!

**Comment by Glfrey** [comment] 2022-08-09 16:02
Hi Mikhail,

I can confirm the error is on my end somewhere. I still haven't identified what is going wrong with that specific dataset but repeating the process with a different dataset is giving me the correct results. Apologies for wasting your attention on this.

**Closed** 2022-08-09 16:02 UTC
